<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_html1frameset1frameset1frame2_packageFrame</name>
   <tag></tag>
   <elementGuidId>53883c12-23e0-4362-8215-941627bed11e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;packageFrame&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'allclasses-frame.html' and @name = 'packageFrame' and @title = 'All classes and interfaces (except non-static nested types)' and @ref_element = 'Object Repository/Page_selenium-api 3.141.59 javadoc (org.sel_3b98a0/iframe_Close_classFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='packageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>222248ec-de0e-4293-a9c2-d4dd7887b7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>allclasses-frame.html</value>
      <webElementGuid>ac517e1b-63ad-4daa-8965-187bd6033e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packageFrame</value>
      <webElementGuid>99be282f-bb0b-435e-8998-b549cfab970f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All classes and interfaces (except non-static nested types)</value>
      <webElementGuid>f3e80323-e922-49cc-8c22-dad1ad2c07b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frame[2]</value>
      <webElementGuid>06ffb456-8929-4741-b0b8-f44a72ba2083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_selenium-api 3.141.59 javadoc (org.sel_3b98a0/iframe_Close_classFrame</value>
      <webElementGuid>d9b00ac2-eba0-4a99-bfb5-9f2b06611e86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='packageFrame']</value>
      <webElementGuid>6ea84551-07a6-4ddd-a593-b3445ce1f32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>ae7d51df-7fd9-418e-9220-7d3094dd13b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'allclasses-frame.html' and @name = 'packageFrame' and @title = 'All classes and interfaces (except non-static nested types)']</value>
      <webElementGuid>dd8d4a5c-8c68-44e5-b29b-21335e651b73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
